-- ADITIF SAJA: nilai enum baru + satu kolom nullable + satu index.
-- Tidak mengubah/menghapus baris FinanceAuditEvent yang sudah ada.
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'ACCOUNT_CREATE';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'ACCOUNT_UPDATE';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'BILL_CREATE';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'INVOICE_CREATE';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'AP_PAYMENT';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'AR_PAYMENT';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'BUDGET_UPSERT';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'BANK_ACCOUNT_CREATE';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'BANK_IMPORT';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'BANK_MATCH';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'TRANSFER';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'SPEND_SUBMIT';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'SPEND_APPROVE';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'SPEND_REJECT';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'SPEND_PAYOUT';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'ASSET_CREATE';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'DEPRECIATION_POST';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'FX_RATE_UPSERT';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'ATTACHMENT_ADD';
ALTER TYPE "FinanceAuditAction" ADD VALUE IF NOT EXISTS 'ATTACHMENT_DELETE';

ALTER TABLE "FinanceAuditEvent" ADD COLUMN IF NOT EXISTS "meta" JSONB;

CREATE INDEX IF NOT EXISTS "FinanceAuditEvent_createdAt_idx" ON "FinanceAuditEvent"("createdAt");
