import type { ConceptData, ValidationScores } from "@/lib/research/concept-lab/types";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildMaklonBriefHtml(input: {
  title: string;
  category: string;
  targetMarket: string | null;
  priceTargetMin: number | null;
  priceTargetMax: number | null;
  conceptData: ConceptData;
  validationScores: ValidationScores;
}): string {
  const name =
    input.conceptData.selectedName ??
    input.conceptData.nameOptions[0] ??
    input.title;
  const priceRange =
    input.priceTargetMin != null && input.priceTargetMax != null
      ? `Rp ${input.priceTargetMin.toLocaleString("id-ID")} – Rp ${input.priceTargetMax.toLocaleString("id-ID")}`
      : "—";
  const cogs = input.conceptData.estimatedCogsRange;
  const cogsStr =
    cogs.min > 0 || cogs.max > 0
      ? `Rp ${cogs.min.toLocaleString("id-ID")} – Rp ${cogs.max.toLocaleString("id-ID")}`
      : "—";

  const ingredients = input.conceptData.heroIngredients
    .map((i) => `<li><strong>${esc(i.name)}</strong> — ${esc(i.reason)}</li>`)
    .join("");

  const claims = input.conceptData.keyClaims
    .map((c) => `<li>${esc(c)}</li>`)
    .join("");

  const risks = input.validationScores.risks
    .map((r) => `<li>${esc(r)}</li>`)
    .join("");

  return `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="utf-8" />
  <title>Maklon Brief — ${esc(name)}</title>
  <style>
    body { font-family: system-ui, sans-serif; color: #111; line-height: 1.5; padding: 32px; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 22px; margin-bottom: 4px; }
    .meta { color: #666; font-size: 13px; margin-bottom: 24px; }
    h2 { font-size: 15px; margin-top: 20px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
    ul { margin: 8px 0; padding-left: 20px; }
    .scores { display: flex; gap: 16px; flex-wrap: wrap; margin: 12px 0; }
    .score { background: #f4f4f5; padding: 8px 12px; border-radius: 8px; font-size: 13px; }
    .score strong { display: block; font-size: 18px; }
    p { margin: 8px 0; }
  </style>
</head>
<body>
  <h1>Maklon Brief: ${esc(name)}</h1>
  <p class="meta">Kategori: ${esc(input.category)} · Target: ${esc(input.targetMarket ?? "—")} · Harga jual: ${priceRange}</p>

  <h2>Positioning</h2>
  <p>${esc(input.conceptData.positioningStatement || "—")}</p>

  <h2>Validator Scores</h2>
  <div class="scores">
    <div class="score"><strong>${input.validationScores.marketDemand}</strong>Market Demand</div>
    <div class="score"><strong>${input.validationScores.differentiation}</strong>Differentiation</div>
    <div class="score"><strong>${input.validationScores.pricingFit}</strong>Pricing Fit</div>
    <div class="score"><strong>${input.validationScores.overall}</strong>Overall</div>
  </div>
  <p>${esc(input.validationScores.aiSummary || "")}</p>

  <h2>Hero Ingredients</h2>
  <ul>${ingredients || "<li>—</li>"}</ul>

  <h2>Texture & Format</h2>
  <p>${esc(input.conceptData.textureFormat || "—")}</p>

  <h2>Key Claims</h2>
  <ul>${claims || "<li>—</li>"}</ul>

  <h2>Packaging Direction</h2>
  <p>${esc(input.conceptData.packagingDirection || "—")}</p>

  <h2>Estimated COGS</h2>
  <p>${cogsStr}</p>

  <h2>Competitor Comparison</h2>
  <p>${esc(input.conceptData.competitorComparison || "—")}</p>

  <h2>Why It Will Win</h2>
  <p>${esc(input.conceptData.whyItWillWin || "—")}</p>

  <h2>Risks</h2>
  <ul>${risks || "<li>—</li>"}</ul>

  <p class="meta" style="margin-top:32px">Generated by DCC Research Hub — Product Concept Lab</p>
</body>
</html>`;
}
